export type Locale = 'en' | 'es';

const translations = {
  en: {
    'app.subtitle': 'Virtual Office · Simulation',
    'demo.label': 'DEMO',
    'demo.title': 'Activity, tokens and costs are generated by the local simulation',
    'nav.office': 'Office View',
    'nav.tasks': 'Tasks & DAG',
    'nav.meetings': 'Meetings',
    'nav.timeline': 'Activity Timeline',
    'controls.pause': 'Pause sequence',
    'controls.play': 'Play demonstration sequence',
    'controls.step': 'Step to next event',
    'controls.reset': 'Reset simulation to initial state',
    'controls.newTask': 'New Task',
    'controls.soundOn': 'Sound effects on',
    'controls.soundMuted': 'Sound effects muted',
    'controls.settings': 'Configure pricing & environment',
    'controls.tokens': 'Tokens',
    'controls.cost': 'Cost',
    'controls.stepLabel': 'Step',
    'canvas.aria': 'Animated agent office. Use the activity panel to inspect tasks and conversations.',
    'canvas.rotateLeft': 'Rotate office left',
    'canvas.rotateRight': 'Rotate office right',
    'canvas.fit': 'Fit full office',
    'canvas.zoomOut': 'Zoom out',
    'canvas.zoomIn': 'Zoom in',
    'canvas.showTimeline': 'Show activity timeline',
    'rooms.boss_office': 'DIRECTOR SUITE',
    'rooms.meeting_room': 'MEETING ROOM A',
    'rooms.meeting_room_b': 'MEETING ROOM B',
    'rooms.server_room': 'MODEL OPS',
    'rooms.leads_area': 'ARCHITECTURE',
    'rooms.development': 'ENGINEERING',
    'rooms.qa_lab': 'QA LAB',
    'rooms.research_area': 'RESEARCH LIBRARY',
    'rooms.break_room': 'ESPRESSO BAR',
    'rooms.lounge': 'TEAM LOUNGE',
  },
  es: {
    'app.subtitle': 'Oficina Virtual · Simulación',
    'demo.label': 'DEMO',
    'demo.title': 'La actividad, los tokens y los costos son generados por la simulación local',
    'nav.office': 'Oficina',
    'nav.tasks': 'Tareas y DAG',
    'nav.meetings': 'Reuniones',
    'nav.timeline': 'Actividad',
    'controls.pause': 'Pausar secuencia',
    'controls.play': 'Reproducir demostración',
    'controls.step': 'Avanzar al siguiente evento',
    'controls.reset': 'Reiniciar simulación',
    'controls.newTask': 'Nueva tarea',
    'controls.soundOn': 'Sonido activado',
    'controls.soundMuted': 'Sonido silenciado',
    'controls.settings': 'Configurar precios y entorno',
    'controls.tokens': 'Tokens',
    'controls.cost': 'Costo',
    'controls.stepLabel': 'Paso',
    'canvas.aria': 'Oficina animada de agentes. Usa el panel de actividad para revisar tareas y conversaciones.',
    'canvas.rotateLeft': 'Girar oficina a la izquierda',
    'canvas.rotateRight': 'Girar oficina a la derecha',
    'canvas.fit': 'Ajustar oficina completa',
    'canvas.zoomOut': 'Alejar',
    'canvas.zoomIn': 'Acercar',
    'canvas.showTimeline': 'Mostrar actividad',
    'rooms.boss_office': 'DIRECCIÓN',
    'rooms.meeting_room': 'SALA DE REUNIÓN A',
    'rooms.meeting_room_b': 'SALA DE REUNIÓN B',
    'rooms.server_room': 'MODEL OPS',
    'rooms.leads_area': 'ARQUITECTURA',
    'rooms.development': 'INGENIERÍA',
    'rooms.qa_lab': 'LAB QA',
    'rooms.research_area': 'BIBLIOTECA I+D',
    'rooms.break_room': 'CAFÉ ESPRESSO',
    'rooms.lounge': 'SALA DEL EQUIPO',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function detectLocale(): Locale {
  if (typeof window === 'undefined') return 'en';
  const saved = window.localStorage.getItem('agent-viewer-locale');
  if (saved === 'en' || saved === 'es') return saved;
  return window.navigator.language.toLowerCase().startsWith('es') ? 'es' : 'en';
}

export function persistLocale(locale: Locale): void {
  if (typeof window !== 'undefined') {
    window.localStorage.setItem('agent-viewer-locale', locale);
  }
}

export function t(locale: Locale, key: TranslationKey): string {
  return translations[locale]?.[key] ?? translations.en[key] ?? key;
}
