import { OFFICE_MESSAGES, formatMessage, type OfficeMessageParams } from './content/officeMessages';
import { AGENT_PANELS_MESSAGES } from './content/app/agentPanels';
import { MODEL_OPS_MESSAGES } from './content/app/modelOps';
import { SHELL_MESSAGES } from './content/app/shell';
import { VIEWS_MESSAGES } from './content/app/views';

export type Locale = 'en' | 'es';

const translations = {
  en: {
    ...OFFICE_MESSAGES.en,
    ...MODEL_OPS_MESSAGES.en,
    ...AGENT_PANELS_MESSAGES.en,
    ...SHELL_MESSAGES.en,
    ...VIEWS_MESSAGES.en,
    'app.subtitle': 'Virtual Office · Simulation',
    'demo.label': 'DEMO',
    'demo.title': 'Activity, tokens and costs are generated by the local simulation',
    'nav.office': 'Office View',
    'nav.tasks': 'Tasks & DAG',
    'nav.meetings': 'Meetings',
    'nav.timeline': 'Activity Timeline',
    'controls.pause': 'Pause sequence',
    'controls.play': 'Play demonstration sequence',
    'controls.step': 'Step to next event',
    'controls.reset': 'Reset simulation to initial state',
    'controls.newTask': 'New Task',
    'controls.soundOn': 'Sound effects on',
    'controls.soundMuted': 'Sound effects muted',
    'controls.settings': 'Configure pricing & environment',
    'controls.tokens': 'Tokens',
    'controls.cost': 'Cost',
    'controls.stepLabel': 'Step',
    'usage.window.label': 'Usage window',
    'usage.window.lastHour': 'Last hour',
    'usage.window.today': 'Today',
    'usage.window.7d': '7 days',
    'usage.window.all': 'All',
    'usage.stale': 'Last known figures: the latest refresh from the usage ledger failed.',
    'floor.main': 'Floor 1 · Main Office',
    'floor.secret': 'Floor 2 · Secret Collaboration',
    'floor.enterSecret': 'Secret Floor',
    'floor.backMain': 'Back to Main Office',
    'floor.activeMeetings': 'active hidden meetings',
    'floor.empty': 'No overflow meetings are active. This floor appears when visible rooms are full.',
    'timeline.search': 'Search event timeline, task IDs, tools...',
    'timeline.allEvents': 'All Events',
    'timeline.tasks': 'Tasks',
    'timeline.meetings': 'Meetings',
    'timeline.tools': 'Tools',
    'timeline.messages': 'Messages',
    'timeline.allAgents': 'All Agents',
    'timeline.export': 'Export JSON',
    'timeline.empty': 'No events match current filter criteria.',
    'timeline.source': 'Source',
    'timeline.target': 'Target',
    'timeline.payload': 'Event Payload',
    'tasks.title': 'Task Pipeline & Dependency Graph',
    'tasks.subtitle': 'Real-time multi-agent execution pipeline, token attribution, and generated artifacts.',
    'tasks.create': 'Create New Task',
    'tasks.dag': 'Standard Organization Execution DAG',
    'tasks.empty': 'No tasks in pipeline. Start the demo sequence or create a new task.',
    'tasks.progress': 'Execution Progress',
    'tasks.assignedLead': 'Assigned Lead',
    'tasks.tokens': 'Tokens Consumed',
    'tasks.totalCost': 'Total Cost',
    'tasks.collaborators': 'Collaborators',
    'tasks.deliverables': 'Produced Deliverables & Artifacts',
    'meetings.title': 'Meeting Operations',
    'meetings.empty': 'No meetings have been recorded yet.',
    'newTask.title': 'Dispatch Custom Task',
    'newTask.subtitle': 'Instruct the multi-agent virtual organization',
    'newTask.templates': 'Quick Goal Templates',
    'newTask.objective': 'Task Objective / Title',
    'newTask.description': 'Description & Acceptance Criteria',
    'newTask.assign': 'Assign Primary Lead Agent',
    'newTask.cancel': 'Cancel',
    'newTask.dispatch': 'Dispatch to Organization',
    'settings.title': 'Agent Viewer Settings & Pricing',
    'settings.subtitle': 'Configure LLM pricing catalog, privacy filters, and telemetry',
    'settings.livingOffice': 'Living Office',
    'settings.ambient': 'Ambient social life',
    'settings.politics': 'Allow politics as an ambient topic',
    'settings.session': 'Session Controls',
    'settings.export': 'Export Session JSON',
    'settings.reset': 'Reset Simulation State',
    'settings.cancel': 'Cancel',
    'settings.save': 'Save Changes',
  },
  es: {
    ...OFFICE_MESSAGES.es,
    ...MODEL_OPS_MESSAGES.es,
    ...AGENT_PANELS_MESSAGES.es,
    ...SHELL_MESSAGES.es,
    ...VIEWS_MESSAGES.es,
    'app.subtitle': 'Oficina Virtual · Simulación',
    'demo.label': 'DEMO',
    'demo.title': 'La actividad, los tokens y los costos son generados por la simulación local',
    'nav.office': 'Oficina',
    'nav.tasks': 'Tareas y DAG',
    'nav.meetings': 'Reuniones',
    'nav.timeline': 'Actividad',
    'controls.pause': 'Pausar secuencia',
    'controls.play': 'Reproducir demostración',
    'controls.step': 'Avanzar al siguiente evento',
    'controls.reset': 'Reiniciar simulación',
    'controls.newTask': 'Nueva tarea',
    'controls.soundOn': 'Sonido activado',
    'controls.soundMuted': 'Sonido silenciado',
    'controls.settings': 'Configurar precios y entorno',
    'controls.tokens': 'Tokens',
    'controls.cost': 'Costo',
    'controls.stepLabel': 'Paso',
    'usage.window.label': 'Ventana de uso',
    'usage.window.lastHour': 'Última hora',
    'usage.window.today': 'Hoy',
    'usage.window.7d': '7 días',
    'usage.window.all': 'Todo',
    'usage.stale': 'Últimas cifras conocidas: la actualización más reciente del ledger de uso falló.',
    'floor.main': 'Piso 1 · Oficina Principal',
    'floor.secret': 'Piso 2 · Colaboración Secreta',
    'floor.enterSecret': 'Piso Secreto',
    'floor.backMain': 'Volver a Oficina Principal',
    'floor.activeMeetings': 'reuniones ocultas activas',
    'floor.empty': 'No hay reuniones de overflow activas. Este piso aparece cuando las salas visibles están llenas.',
    'timeline.search': 'Buscar en actividad, IDs de tareas, herramientas...',
    'timeline.allEvents': 'Todos',
    'timeline.tasks': 'Tareas',
    'timeline.meetings': 'Reuniones',
    'timeline.tools': 'Herramientas',
    'timeline.messages': 'Mensajes',
    'timeline.allAgents': 'Todos los agentes',
    'timeline.export': 'Exportar JSON',
    'timeline.empty': 'No hay eventos que coincidan con los filtros actuales.',
    'timeline.source': 'Origen',
    'timeline.target': 'Destino',
    'timeline.payload': 'Datos del evento',
    'tasks.title': 'Pipeline de Tareas y Grafo de Dependencias',
    'tasks.subtitle': 'Ejecución multiagente en tiempo real, atribución de tokens y artefactos generados.',
    'tasks.create': 'Crear Nueva Tarea',
    'tasks.dag': 'DAG Estándar de Ejecución',
    'tasks.empty': 'No hay tareas en el pipeline. Inicia la demo o crea una nueva tarea.',
    'tasks.progress': 'Progreso de Ejecución',
    'tasks.assignedLead': 'Agente Principal',
    'tasks.tokens': 'Tokens Consumidos',
    'tasks.totalCost': 'Costo Total',
    'tasks.collaborators': 'Colaboradores',
    'tasks.deliverables': 'Entregables y Artefactos Generados',
    'meetings.title': 'Operaciones de Reunión',
    'meetings.empty': 'Todavía no se han registrado reuniones.',
    'newTask.title': 'Asignar Tarea Personalizada',
    'newTask.subtitle': 'Instruye a la organización virtual multiagente',
    'newTask.templates': 'Plantillas Rápidas',
    'newTask.objective': 'Objetivo / Título de la Tarea',
    'newTask.description': 'Descripción y Criterios de Aceptación',
    'newTask.assign': 'Asignar Agente Principal',
    'newTask.cancel': 'Cancelar',
    'newTask.dispatch': 'Enviar a la Organización',
    'settings.title': 'Configuración y Precios de Agent Viewer',
    'settings.subtitle': 'Configura precios LLM, filtros de privacidad y telemetría',
    'settings.livingOffice': 'Oficina Viva',
    'settings.ambient': 'Vida social ambiental',
    'settings.politics': 'Permitir política como tema ambiental',
    'settings.session': 'Controles de Sesión',
    'settings.export': 'Exportar Sesión JSON',
    'settings.reset': 'Reiniciar Estado de Simulación',
    'settings.cancel': 'Cancelar',
    'settings.save': 'Guardar Cambios',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function detectLocale(): Locale {
  if (typeof window === 'undefined') return 'en';
  const saved = window.localStorage.getItem('agent-viewer-locale');
  if (saved === 'en' || saved === 'es') return saved;
  return window.navigator.language.toLowerCase().startsWith('es') ? 'es' : 'en';
}

export function persistLocale(locale: Locale): void {
  if (typeof window !== 'undefined') {
    window.localStorage.setItem('agent-viewer-locale', locale);
  }
}

/** Full app catalogs, exported so tests can check that both languages have the same keys. */
export const APP_MESSAGES: { readonly en: Record<TranslationKey, string>; readonly es: Record<TranslationKey, string> } =
  translations;

/** Translates `key` and fills `{name}` placeholders with `params`. */
export function t(locale: Locale, key: TranslationKey, params?: OfficeMessageParams): string {
  const template = translations[locale]?.[key] ?? translations.en[key] ?? key;
  return formatMessage(template, params);
}

/** Keeps the `lang` attribute of the document in sync with the UI language (WCAG 3.1.1). */
export function applyDocumentLocale(locale: Locale): void {
  if (typeof document !== 'undefined') {
    document.documentElement.lang = locale;
  }
}
