/**
 * Demo app texts (not the library) for this area, in English and Spanish.
 * The keys are merged into the app catalog in `src/i18n.ts`. Placeholders use `{name}` and are filled by
 * `t(locale, key, params)`.
 */

const EN = {
  // Shared by the detail modal and the side inspector
  'agentPanels.stationedFallback': 'Stationed at assigned pod',
  'agentPanels.team.leadership': 'Leadership',
  'agentPanels.team.engineering': 'Engineering',
  'agentPanels.team.research': 'Research',
  'agentPanels.team.quality': 'Quality',
  'agentPanels.team.operations': 'Operations',
  'agentPanels.team.other': 'Other',
  'agentPanels.facing.SE': 'Southeast',
  'agentPanels.facing.SW': 'Southwest',
  'agentPanels.facing.NE': 'Northeast',
  'agentPanels.facing.NW': 'Northwest',
  'agentPanels.taskStatus.PENDING': 'Pending',
  'agentPanels.taskStatus.ASSIGNED': 'Assigned',
  'agentPanels.taskStatus.IN_PROGRESS': 'In progress',
  'agentPanels.taskStatus.BLOCKED': 'Blocked',
  'agentPanels.taskStatus.REVIEW': 'In review',
  'agentPanels.taskStatus.COMPLETED': 'Completed',
  'agentPanels.taskStatus.FAILED': 'Failed',
  'agentPanels.artifactType.code': 'Code',
  'agentPanels.artifactType.report': 'Report',
  'agentPanels.artifactType.pr': 'Pull request',
  'agentPanels.artifactType.test_run': 'Test run',
  'agentPanels.artifactType.schema': 'Schema',
  'agentPanels.artifactType.architecture': 'Architecture',

  // Agent detail modal
  'agentDetail.copyId': 'Copy agent ID',
  'agentDetail.copyIdLabel': 'Copy agent ID {id}',
  'agentDetail.idCopied': 'Agent ID copied',
  'agentDetail.teamLabel': '{team} team',
  'agentDetail.previous': 'Previous',
  'agentDetail.previousAgent': 'Previous agent: {name}',
  'agentDetail.next': 'Next',
  'agentDetail.nextAgent': 'Next agent: {name}',
  'agentDetail.focus': 'Focus',
  'agentDetail.focusTitle': 'Center and focus on the agent in the 2.5D office',
  'agentDetail.closeTitle': 'Close agent details (Esc)',
  'agentDetail.activity': 'Activity:',
  'agentDetail.speech': 'Speech bubble',
  'agentDetail.tabsLabel': 'Agent detail sections',
  'agentDetail.tab.overview': 'Overview',
  'agentDetail.tab.tasks': 'Task & Artifacts ({count})',
  'agentDetail.tab.metrics': 'Metrics & Tokens',
  'agentDetail.tab.logs': 'Activity Log ({count})',
  'agentDetail.tab.console': 'Interactive Console',
  'agentDetail.profileHeading': 'Profile & Org Structure',
  'agentDetail.mainRole': 'Main role',
  'agentDetail.department': 'Department',
  'agentDetail.reportsTo': 'Reports directly to',
  'agentDetail.boardOfDirectors': 'Board of Directors',
  'agentDetail.supervises': 'Supervises',
  'agentDetail.subordinates': '{count} agents ({names})',
  'agentDetail.autonomous': 'Autonomous individual work',
  'agentDetail.officeLocation': 'Office location',
  'agentDetail.zone': 'Zone: {zone}',
  'agentDetail.tile': 'Tile ({x}, {y})',
  'agentDetail.facing': 'Facing: {direction}',
  'agentDetail.mode': 'Mode: {mode}',
  'agentDetail.modeWalking': 'Moving around',
  'agentDetail.modeStationed': 'At workstation',
  'agentDetail.inferenceHeading': 'LLM Inference Specs',
  'agentDetail.provider': 'Provider',
  'agentDetail.activeModel': 'Active model',
  'agentDetail.contextWindow': 'Context window',
  'agentDetail.contextWindowValue': '128k - 1M tokens',
  'agentDetail.baseTemperature': 'Base temperature',
  'agentDetail.baseTemperatureValue': '0.2 (Technical precision)',
  'agentDetail.changeStatus': 'Change status manually',
  'agentDetail.progress': 'Progress:',
  'agentDetail.progressLabel': 'Task progress',
  'agentDetail.tools': 'Tools:',

  // Tool spend tooltip (issue #81, real figures from the usage ledger, #80)
  'tool.spend.calls': '{count} model calls',
  'tool.spend.tokens': 'Tokens',
  'tool.spend.cost': 'Cost',
  'tool.spend.loading': 'Loading spend…',
  'tool.spend.unavailable': 'Spend data is not available from this server.',
  'tool.spend.none': 'No figures from the server',

  'agentDetail.noActiveTask': 'This agent has no active task assigned right now.',
  'agentDetail.noActiveTaskHint': 'You can assign a new mission or dispatch one from the task manager.',
  'agentDetail.assignTask': 'Assign New Task to {name}',
  'agentDetail.artifactsHeading': 'Produced Artifacts & Deliverables ({count})',
  'agentDetail.noArtifacts': 'No artifacts generated yet in this simulation session.',
  'agentDetail.inputTokens': 'Input tokens',
  'agentDetail.inputTokensHint': 'Context prompts',
  'agentDetail.outputTokens': 'Output tokens',
  'agentDetail.outputTokensHint': 'Code/text generation',
  'agentDetail.reasoningTokens': 'Reasoning tokens',
  'agentDetail.reasoningTokensHint': 'Deep thinking',
  'agentDetail.accumulatedCost': 'Accumulated cost',
  'agentDetail.accumulatedCostHint': 'USD billed',
  'agentDetail.performanceHeading': 'Performance & Operating Speed',
  'agentDetail.activeTime': 'Active time (session)',
  'agentDetail.minutes': '{minutes} min',
  'agentDetail.averageSpeed': 'Average speed',
  'agentDetail.tokensPerMinute': '{value} t/min',
  'agentDetail.completedTasks': 'Completed tasks',
  'agentDetail.completedOf': '{done} of {total}',
  'agentDetail.eventsHeading': 'Linked Event History ({count})',
  'agentDetail.eventTarget': 'Target: {target}',
  'agentDetail.noEvents': 'No events recorded for this agent in the current session.',
  'agentDetail.consoleHeading': 'Send a Direct Instruction or Prompt',
  'agentDetail.consoleIntro':
    'Send an immediate order to {name}. This instruction will be processed with priority by the inference engine.',
  'agentDetail.quickOrders': 'Suggested quick orders:',
  'agentDetail.quick.report': 'Generate report',
  'agentDetail.quick.reportPrompt': 'Generate a current status report and deliverables',
  'agentDetail.quick.coverage': 'Validate coverage',
  'agentDetail.quick.coveragePrompt': 'Run the test suite and validate coverage',
  'agentDetail.quick.review': 'Request review',
  'agentDetail.quick.reviewPrompt': 'Sync changes and request a review from the Director',
  'agentDetail.quick.optimize': 'Optimize resources',
  'agentDetail.quick.optimizePrompt': 'Optimize token usage and pause subprocesses',
  'agentDetail.promptLabel': 'Direct instruction for {name}',
  'agentDetail.promptPlaceholder': 'Write a direct instruction for {name}...',
  'agentDetail.sent': 'Instruction sent to {name}',
  'agentDetail.quickSent': 'Quick instruction sent: "{text}"',
  'agentDetail.sendHint': 'Press Send to dispatch the order.',
  'agentDetail.send': 'Send Order',
  'agentDetail.tip': 'Tip:',
  'agentDetail.tipText': 'Double click any agent in the office to open this window directly.',
  'agentDetail.close': 'Close',

  // Side inspector
  'inspector.label': 'Agent inspector: {name}',
  'inspector.headerTitle': 'Double click to open the full record in a window',
  'inspector.openDetail': 'Open full record in a window',
  'inspector.close': 'Close side panel',
  'inspector.currentStatus': 'Current status',
  'inspector.modelConfig': 'Model configuration',
  'inspector.provider': 'Provider',
  'inspector.engineModel': 'Engine / Model',
  'inspector.telemetry': 'Session telemetry',
  'inspector.activeMinutes': '{minutes}m active',
  'inspector.totalTokens': 'Total tokens',
  'inspector.estimatedCost': 'Estimated cost',
  'inspector.inputTokens': 'Input tokens:',
  'inspector.outputTokens': 'Output tokens:',
  'inspector.cachedTokens': 'Cached tokens:',
  'inspector.reasoningTokens': 'Reasoning tokens:',
  'inspector.operatorControls': 'Operator controls',
  'inspector.focusCamera': 'Focus camera',
  'inspector.statusSelect': 'Change agent status',
  'inspector.setStatus': 'Set {status}',
  'inspector.recentActivity': 'Recent activity',
  'inspector.noEvents': 'No recent events recorded.',
  'inspector.instructionLabel': 'Instruction for {name}',
  'inspector.instructionPlaceholder': 'Instruct {name}...',
  'inspector.send': 'Send instruction',
} as const satisfies Record<string, string>;

const ES: Record<keyof typeof EN, string> = {
  // Compartidas por la ventana de detalle y el inspector lateral
  'agentPanels.stationedFallback': 'En estación de trabajo asignada',
  'agentPanels.team.leadership': 'Dirección',
  'agentPanels.team.engineering': 'Ingeniería',
  'agentPanels.team.research': 'Investigación',
  'agentPanels.team.quality': 'Calidad',
  'agentPanels.team.operations': 'Operaciones',
  'agentPanels.team.other': 'Otro',
  'agentPanels.facing.SE': 'Sureste',
  'agentPanels.facing.SW': 'Suroeste',
  'agentPanels.facing.NE': 'Noreste',
  'agentPanels.facing.NW': 'Noroeste',
  'agentPanels.taskStatus.PENDING': 'Pendiente',
  'agentPanels.taskStatus.ASSIGNED': 'Asignada',
  'agentPanels.taskStatus.IN_PROGRESS': 'En curso',
  'agentPanels.taskStatus.BLOCKED': 'Bloqueada',
  'agentPanels.taskStatus.REVIEW': 'En revisión',
  'agentPanels.taskStatus.COMPLETED': 'Completada',
  'agentPanels.taskStatus.FAILED': 'Fallida',
  'agentPanels.artifactType.code': 'Código',
  'agentPanels.artifactType.report': 'Informe',
  'agentPanels.artifactType.pr': 'Pull request',
  'agentPanels.artifactType.test_run': 'Ejecución de pruebas',
  'agentPanels.artifactType.schema': 'Esquema',
  'agentPanels.artifactType.architecture': 'Arquitectura',

  // Ventana de detalle del agente
  'agentDetail.copyId': 'Copiar ID del agente',
  'agentDetail.copyIdLabel': 'Copiar ID del agente {id}',
  'agentDetail.idCopied': 'ID del agente copiado',
  'agentDetail.teamLabel': 'Equipo de {team}',
  'agentDetail.previous': 'Anterior',
  'agentDetail.previousAgent': 'Agente anterior: {name}',
  'agentDetail.next': 'Siguiente',
  'agentDetail.nextAgent': 'Agente siguiente: {name}',
  'agentDetail.focus': 'Enfocar',
  'agentDetail.focusTitle': 'Centrar y enfocar al agente en la oficina 2.5D',
  'agentDetail.closeTitle': 'Cerrar el detalle del agente (Esc)',
  'agentDetail.activity': 'Actividad:',
  'agentDetail.speech': 'Globo de diálogo',
  'agentDetail.tabsLabel': 'Secciones del detalle del agente',
  'agentDetail.tab.overview': 'Visión general',
  'agentDetail.tab.tasks': 'Tarea y artefactos ({count})',
  'agentDetail.tab.metrics': 'Métricas y tokens',
  'agentDetail.tab.logs': 'Registro de actividad ({count})',
  'agentDetail.tab.console': 'Consola interactiva',
  'agentDetail.profileHeading': 'Perfil y estructura organizacional',
  'agentDetail.mainRole': 'Rol principal',
  'agentDetail.department': 'Departamento',
  'agentDetail.reportsTo': 'Reporta directamente a',
  'agentDetail.boardOfDirectors': 'Junta directiva',
  'agentDetail.supervises': 'Supervisa',
  'agentDetail.subordinates': '{count} agentes ({names})',
  'agentDetail.autonomous': 'Trabajo autónomo individual',
  'agentDetail.officeLocation': 'Ubicación en la oficina',
  'agentDetail.zone': 'Zona: {zone}',
  'agentDetail.tile': 'Casilla ({x}, {y})',
  'agentDetail.facing': 'Orientación: {direction}',
  'agentDetail.mode': 'Modo: {mode}',
  'agentDetail.modeWalking': 'Desplazándose',
  'agentDetail.modeStationed': 'En estación de trabajo',
  'agentDetail.inferenceHeading': 'Especificaciones de inferencia LLM',
  'agentDetail.provider': 'Proveedor',
  'agentDetail.activeModel': 'Modelo activo',
  'agentDetail.contextWindow': 'Ventana de contexto',
  'agentDetail.contextWindowValue': '128k - 1M tokens',
  'agentDetail.baseTemperature': 'Temperatura base',
  'agentDetail.baseTemperatureValue': '0.2 (precisión técnica)',
  'agentDetail.changeStatus': 'Cambiar estado manualmente',
  'agentDetail.progress': 'Progreso:',
  'agentDetail.progressLabel': 'Progreso de la tarea',
  'agentDetail.tools': 'Herramientas:',

  'tool.spend.calls': '{count} llamadas al modelo',
  'tool.spend.tokens': 'Tokens',
  'tool.spend.cost': 'Costo',
  'tool.spend.loading': 'Cargando el gasto…',
  'tool.spend.unavailable': 'Este servidor no tiene datos de gasto disponibles.',
  'tool.spend.none': 'Sin cifras del servidor',

  'agentDetail.noActiveTask': 'Este agente no tiene una tarea activa asignada en este momento.',
  'agentDetail.noActiveTaskHint': 'Puedes asignarle una nueva misión o despacharla desde el gestor de tareas.',
  'agentDetail.assignTask': 'Asignar nueva tarea a {name}',
  'agentDetail.artifactsHeading': 'Artefactos y entregables producidos ({count})',
  'agentDetail.noArtifacts': 'Aún no ha generado artefactos en esta sesión de simulación.',
  'agentDetail.inputTokens': 'Tokens de entrada',
  'agentDetail.inputTokensHint': 'Prompts de contexto',
  'agentDetail.outputTokens': 'Tokens de salida',
  'agentDetail.outputTokensHint': 'Generación de código o texto',
  'agentDetail.reasoningTokens': 'Tokens de razonamiento',
  'agentDetail.reasoningTokensHint': 'Pensamiento profundo',
  'agentDetail.accumulatedCost': 'Costo acumulado',
  'agentDetail.accumulatedCostHint': 'USD facturados',
  'agentDetail.performanceHeading': 'Rendimiento y velocidad operativa',
  'agentDetail.activeTime': 'Tiempo activo (sesión)',
  'agentDetail.minutes': '{minutes} min',
  'agentDetail.averageSpeed': 'Velocidad promedio',
  'agentDetail.tokensPerMinute': '{value} t/min',
  'agentDetail.completedTasks': 'Tareas completadas',
  'agentDetail.completedOf': '{done} de {total}',
  'agentDetail.eventsHeading': 'Historial de eventos vinculados ({count})',
  'agentDetail.eventTarget': 'Destino: {target}',
  'agentDetail.noEvents': 'No hay eventos registrados para este agente en la sesión actual.',
  'agentDetail.consoleHeading': 'Enviar instrucción o prompt directo',
  'agentDetail.consoleIntro':
    'Envía una orden inmediata a {name}. Esta instrucción será procesada con prioridad por el motor de inferencia.',
  'agentDetail.quickOrders': 'Órdenes rápidas sugeridas:',
  'agentDetail.quick.report': 'Generar informe',
  'agentDetail.quick.reportPrompt': 'Generar informe de estado actual y entregables',
  'agentDetail.quick.coverage': 'Validar cobertura',
  'agentDetail.quick.coveragePrompt': 'Ejecutar la suite de pruebas y validar la cobertura',
  'agentDetail.quick.review': 'Solicitar revisión',
  'agentDetail.quick.reviewPrompt': 'Sincronizar cambios y solicitar revisión al Director',
  'agentDetail.quick.optimize': 'Optimizar recursos',
  'agentDetail.quick.optimizePrompt': 'Optimizar el consumo de tokens y pausar subprocesos',
  'agentDetail.promptLabel': 'Instrucción directa para {name}',
  'agentDetail.promptPlaceholder': 'Escribe una instrucción directa para {name}...',
  'agentDetail.sent': 'Instrucción enviada a {name}',
  'agentDetail.quickSent': 'Instrucción rápida enviada: "{text}"',
  'agentDetail.sendHint': 'Presiona Enviar para despachar la orden.',
  'agentDetail.send': 'Enviar orden',
  'agentDetail.tip': 'Consejo:',
  'agentDetail.tipText': 'Haz doble clic en cualquier agente de la oficina para abrir esta ventana directamente.',
  'agentDetail.close': 'Cerrar',

  // Inspector lateral
  'inspector.label': 'Inspector del agente: {name}',
  'inspector.headerTitle': 'Doble clic para abrir el expediente completo en una ventana',
  'inspector.openDetail': 'Abrir el expediente completo en una ventana',
  'inspector.close': 'Cerrar panel lateral',
  'inspector.currentStatus': 'Estado actual',
  'inspector.modelConfig': 'Configuración del modelo',
  'inspector.provider': 'Proveedor',
  'inspector.engineModel': 'Motor / Modelo',
  'inspector.telemetry': 'Telemetría de la sesión',
  'inspector.activeMinutes': '{minutes} min activo',
  'inspector.totalTokens': 'Tokens totales',
  'inspector.estimatedCost': 'Costo estimado',
  'inspector.inputTokens': 'Tokens de entrada:',
  'inspector.outputTokens': 'Tokens de salida:',
  'inspector.cachedTokens': 'Tokens en caché:',
  'inspector.reasoningTokens': 'Tokens de razonamiento:',
  'inspector.operatorControls': 'Controles del operador',
  'inspector.focusCamera': 'Enfocar cámara',
  'inspector.statusSelect': 'Cambiar el estado del agente',
  'inspector.setStatus': 'Cambiar a: {status}',
  'inspector.recentActivity': 'Actividad reciente',
  'inspector.noEvents': 'No hay eventos recientes registrados.',
  'inspector.instructionLabel': 'Instrucción para {name}',
  'inspector.instructionPlaceholder': 'Instruir a {name}...',
  'inspector.send': 'Enviar instrucción',
};

export const AGENT_PANELS_MESSAGES = { en: EN, es: ES };
