/**
 * Demo app texts (not the library) for the top bar, the live timeline sidebar and other shell pieces, in English
 * and Spanish. The keys are merged into the app catalog in `src/i18n.ts`. Placeholders use `{name}` and are filled
 * by `t(locale, key, params)`.
 */

const EN = {
  // Top bar
  'nav.label': 'Main views',
  'live.badge': 'LIVE',
  'live.title': 'Live stream active',
  'live.connecting': 'CONNECTING',
  'security.openApi.label': 'OPEN API',
  'security.openApi.title': 'This server has no API token',
  'security.openApi.body': 'Anyone who can reach it can send events, change the token and cost figures shown here, and read every usage record.',
  'security.openApi.action': 'Set AGENT_VIEWER_API_TOKEN and restart the server.',
  'security.openApi.docsLink': 'How to set a token',
  'controls.speedGroup': 'Playback speed',
  'controls.speedValue': 'Speed {speed}x',
  'controls.speedShort': '{speed}x',
  'controls.stepCounter': '{label} {current}/{total}',
  'controls.modelOpsTitle': 'Open Model Ops: token usage by provider and model',
  'controls.modelOpsLabel': 'Model Ops',
  'controls.language': 'Language',
  'controls.languageEn': 'English',
  'controls.languageEs': 'Spanish',

  // Live timeline sidebar
  'sidebar.label': 'Live activity and agent inspector',
  'sidebar.views': 'Sidebar views',
  'sidebar.liveTab': 'Live activity',
  'sidebar.inspectorTab': 'Inspector',
  'sidebar.hide': 'Hide activity sidebar',
  'sidebar.hideShort': 'Hide',
  'sidebar.officeTitle': 'Virtual Office',
  'sidebar.officeSummary': '{count} agents · 2.5D view',
  'sidebar.meeting': 'Meeting',
  'sidebar.live': 'Live',
  'sidebar.filterLabel': 'Show:',
  'sidebar.filterAll': 'All ({count})',
  'sidebar.waiting': 'Waiting for new agent events...',
  'sidebar.cardHint': 'Double click to open the full agent profile',
  'sidebar.selectAgent': 'Select and focus {name}',
  'sidebar.focusInOffice': 'Focus in office',
  'sidebar.focusAgentInOffice': 'Focus in office: {name}',
  'sidebar.detailHint': 'Double click to see every detail',
  'sidebar.openProfile': 'Open the full agent profile',
  'sidebar.currentStatus': 'Current status',
  'sidebar.cost': 'Cost',
  'sidebar.currentActivity': 'Current activity',
  'sidebar.sendMessage': 'Send a message to the agent',
  'sidebar.messagePlaceholder': 'Type an instruction or prompt...',
  'sidebar.send': 'Send message',
  'sidebar.backToTimeline': 'Back to the timeline',
  'sidebar.badge.critical': 'Critical alert',
  'sidebar.badge.tool': 'Tool',
  'sidebar.badge.completed': 'Completed',
  'sidebar.badge.blocked': 'Blocked',
  'sidebar.badge.task': 'Task',
  'sidebar.badge.meeting': 'Meeting',
  'sidebar.badge.message': 'Message',
  'sidebar.badge.event': 'Event',
  'sidebar.taskProgress': 'Progress of {task}',

  // Relative times
  'time.justNow': 'Just now',
  'time.secondsAgo': '{count}s ago',
  'time.minutesAgo': '{count}m ago',
  'time.hoursAgo': '{count}h ago',

  // Event log drop zone and errors
  'drop.title': 'Drop a JSONL or OTLP log to replay it',
  'drop.subtitle': 'Replay past agent sessions without a server',
  'drop.noEvents': 'The file contains 0 valid canonical events',
  'drop.readFailed': 'The event log file could not be read',
  'drop.dismiss': 'Dismiss error',

  // Operator actions recorded by the demo app
  'operator.messageEvent': 'Operator instruction sent to {agent}: "{message}"',
  'operator.statusText': 'Operator set the status to {status}',
  'operator.statusEvent': 'Operator changed the status of {agent} to {status}.',
  'operator.simulatedBubble': 'Simulated: +{tokens} tokens on {model}',
  'operator.modelStatusText': 'Model changed to {model} ({provider})',
  'operator.modelBubble': 'I switched my engine to {model} ({provider})',
  'operator.modelEvent': 'Agent reassigned: {model} ({provider})',
} as const satisfies Record<string, string>;

const ES: Record<keyof typeof EN, string> = {
  'nav.label': 'Vistas principales',
  'live.badge': 'EN VIVO',
  'live.title': 'Transmisión en vivo activa',
  'live.connecting': 'CONECTANDO',
  'security.openApi.label': 'API ABIERTA',
  'security.openApi.title': 'Este servidor no tiene token de API',
  'security.openApi.body': 'Cualquiera que llegue a él puede enviar eventos, cambiar las cifras de tokens y costos que ves aquí y leer todo el consumo.',
  'security.openApi.action': 'Define AGENT_VIEWER_API_TOKEN y reinicia el servidor.',
  'security.openApi.docsLink': 'Cómo definir un token',
  'controls.speedGroup': 'Velocidad de reproducción',
  'controls.speedValue': 'Velocidad {speed}x',
  'controls.speedShort': '{speed}x',
  'controls.stepCounter': '{label} {current}/{total}',
  'controls.modelOpsTitle': 'Abrir Model Ops: consumo de tokens por proveedor y modelo',
  'controls.modelOpsLabel': 'Model Ops',
  'controls.language': 'Idioma',
  'controls.languageEn': 'Inglés',
  'controls.languageEs': 'Español',

  'sidebar.label': 'Actividad en vivo e inspector de agentes',
  'sidebar.views': 'Vistas de la barra lateral',
  'sidebar.liveTab': 'Actividad en vivo',
  'sidebar.inspectorTab': 'Inspector',
  'sidebar.hide': 'Ocultar la barra lateral de actividad',
  'sidebar.hideShort': 'Ocultar',
  'sidebar.officeTitle': 'Oficina Virtual',
  'sidebar.officeSummary': '{count} agentes · Vista 2.5D',
  'sidebar.meeting': 'Reunión',
  'sidebar.live': 'En vivo',
  'sidebar.filterLabel': 'Ver:',
  'sidebar.filterAll': 'Todos ({count})',
  'sidebar.waiting': 'Esperando nuevos eventos de los agentes...',
  'sidebar.cardHint': 'Doble clic para abrir el expediente completo del agente',
  'sidebar.selectAgent': 'Seleccionar y enfocar a {name}',
  'sidebar.focusInOffice': 'Enfocar en la oficina',
  'sidebar.focusAgentInOffice': 'Enfocar en la oficina: {name}',
  'sidebar.detailHint': 'Doble clic para ver todo el detalle',
  'sidebar.openProfile': 'Abrir el expediente completo del agente',
  'sidebar.currentStatus': 'Estado actual',
  'sidebar.cost': 'Costo',
  'sidebar.currentActivity': 'Actividad en curso',
  'sidebar.sendMessage': 'Enviar un mensaje al agente',
  'sidebar.messagePlaceholder': 'Escribe una instrucción o prompt...',
  'sidebar.send': 'Enviar mensaje',
  'sidebar.backToTimeline': 'Volver a la línea de tiempo',
  'sidebar.badge.critical': 'Alerta crítica',
  'sidebar.badge.tool': 'Herramienta',
  'sidebar.badge.completed': 'Completado',
  'sidebar.badge.blocked': 'Bloqueado',
  'sidebar.badge.task': 'Tarea',
  'sidebar.badge.meeting': 'Reunión',
  'sidebar.badge.message': 'Mensaje',
  'sidebar.badge.event': 'Evento',
  'sidebar.taskProgress': 'Progreso de {task}',

  'time.justNow': 'Justo ahora',
  'time.secondsAgo': 'Hace {count}s',
  'time.minutesAgo': 'Hace {count}m',
  'time.hoursAgo': 'Hace {count}h',

  'drop.title': 'Suelta un log JSONL u OTLP para reproducirlo',
  'drop.subtitle': 'Reproduce sesiones pasadas de agentes sin servidor',
  'drop.noEvents': 'El archivo no contiene eventos canónicos válidos',
  'drop.readFailed': 'No se pudo leer el archivo de eventos',
  'drop.dismiss': 'Cerrar el error',

  'operator.messageEvent': 'Instrucción del operador enviada a {agent}: "{message}"',
  'operator.statusText': 'El operador cambió el estado a {status}',
  'operator.statusEvent': 'El operador cambió el estado de {agent} a {status}.',
  'operator.simulatedBubble': 'Simulado: +{tokens} tokens en {model}',
  'operator.modelStatusText': 'Modelo cambiado a {model} ({provider})',
  'operator.modelBubble': 'Cambié mi motor a {model} ({provider})',
  'operator.modelEvent': 'Agente reasignado: {model} ({provider})',
};

export const SHELL_MESSAGES = { en: EN, es: ES };
