/**
 * Demo app texts (not the library) for the main views and their dialogs: tasks, meetings, activity timeline,
 * the secret floor, new task and settings, in English and Spanish. The keys are merged into the app catalog in
 * `src/i18n.ts`. Placeholders use `{name}` and are filled by `t(locale, key, params)`.
 */

const EN = {
  // Shared
  'common.close': 'Close',
  'common.closeDialog': 'Close dialog',

  // Task board
  'tasks.createButton': '+ {label}',
  'tasks.dag.director': 'Director',
  'tasks.dag.directorDetail': 'Objective',
  'tasks.dag.leads': 'Tech and research leads',
  'tasks.dag.leadsDetail': 'Architecture and specs',
  'tasks.dag.engineering': 'Engineering pod',
  'tasks.dag.engineeringDetail': 'Code and tools',
  'tasks.dag.qa': 'QA lab',
  'tasks.dag.qaDetail': 'Security and tests',
  'tasks.dag.release': 'Release verified',
  'tasks.cardHint': 'Double click to open the profile of the assigned agent',
  'tasks.leadHint': 'Open the full profile of {name}',
  'tasks.blocked': 'Execution blocked',
  'tasks.deliverablesCount': '{label} ({count})',
  'tasks.author': 'Author: {name}',
  'tasks.progressLabel': 'Progress of {task}',
  'taskStatus.PENDING': 'Pending',
  'taskStatus.ASSIGNED': 'Assigned',
  'taskStatus.IN_PROGRESS': 'In progress',
  'taskStatus.BLOCKED': 'Blocked',
  'taskStatus.REVIEW': 'In review',
  'taskStatus.COMPLETED': 'Completed',
  'taskStatus.FAILED': 'Failed',

  // Meetings
  'meetings.live': 'Live in session',
  'meetings.subtitle': 'Multi-agent deliberation, architectural alignment, consensus building and decisions.',
  'meetings.startedAt': 'Started {time}',
  'meetings.agenda': 'Agenda items',
  'meetings.agendaItem': '{index}. {item}',
  'meetings.transcript': 'Deliberation transcript',
  'meetings.exchanges': '{count} exchanges',
  'meetings.decisions': 'Consensus and decisions recorded',
  'meetings.telemetry': 'Meeting telemetry',
  'meetings.tokens': 'Tokens burned',
  'meetings.cost': 'Session cost',
  'meetings.tasksSpawned': 'Tasks spawned',
  'meetings.attendees': 'Seated attendees ({count})',
  'meetings.participant': 'Participant',
  'meetings.status.SCHEDULED': 'Scheduled',
  'meetings.status.ACTIVE': 'Active',
  'meetings.status.CONCLUDED': 'Concluded',

  // Meeting spend (issue #81, real figures from the usage ledger, #80)
  'meetings.spend.calls': '{count} model calls',
  'meetings.spend.inputTokens': 'Input tokens',
  'meetings.spend.outputTokens': 'Output tokens',
  'meetings.spend.cost': 'Cost',
  'meetings.spend.loading': 'Loading spend…',
  'meetings.spend.unavailable': 'Spend data is not available from this server.',
  'meetings.spend.simulated': 'Simulated',
  'meetings.spend.asOf': 'As of {time}',
  'meetings.spend.table': 'Spend per meeting',
  'meetings.spend.tableTitle': 'Meeting',
  'meetings.spend.tableTokens': 'Tokens',
  'meetings.spend.tableCost': 'Cost',
  'meetings.spend.unattributedRow': 'Not attributed to a meeting',
  'meetings.spend.incomplete': 'History may be incomplete.',

  // Activity timeline
  'timeline.searchLabel': 'Search the event timeline',
  'timeline.categories': 'Event categories',
  'timeline.agentFilter': 'Filter events by agent',
  'timeline.expand': 'Show event details',
  'timeline.collapse': 'Hide event details',

  // Secret floor
  'floor.subtitle': 'Elastic overflow rooms are created only when all visible meeting spaces are busy.',
  'floor.privateTopic': 'Private overflow collaboration',
  'floor.agentsUpstairs': '{count} agents upstairs',
  'floor.reservation.RESERVED': 'Reserved',
  'floor.reservation.ACTIVE': 'Active',

  // New task
  'newTask.objectivePlaceholder': 'e.g. Implement a webhook dispatcher with exponential backoff',
  'newTask.descriptionPlaceholder': 'Outline the technical deliverables, security constraints and endpoints...',
  'newTask.defaultDescription': 'Custom goal dispatched from the console.',
  'newTask.agentOption': '{name}, {role}',
  'newTask.roleFallback.backend_engineer': 'Backend engineer',
  'newTask.roleFallback.frontend_engineer': 'Frontend engineer',
  'newTask.roleFallback.research_lead': 'Research lead',
  'newTask.roleFallback.qa_engineer': 'QA and test automation',
  'newTask.roleFallback.security_analyst': 'Security analyst',
  'newTask.preset.security.title': 'Run a security audit and secret leak scan',
  'newTask.preset.security.description': 'Scan the codebase and the git history for hardcoded tokens, OAuth credentials and CVE alerts.',
  'newTask.preset.database.title': 'PostgreSQL migration and index tuning',
  'newTask.preset.database.description': 'Draft DDL migration scripts, add compound indexes on query paths and measure p99 latency.',
  'newTask.preset.rag.title': 'RAG vector index pipeline and citation ingest',
  'newTask.preset.rag.description': 'Embed the technical RFC documentation into a vector store for sub-second retrieval.',
  'newTask.preset.e2e.title': 'Automated Playwright end-to-end visual regression suite',
  'newTask.preset.e2e.description': 'Run headless browser tests across every desktop and mobile viewport.',

  // Settings
  'settings.close': 'Close settings',
  'settings.pricingTitle': 'LLM model pricing catalog ($ per 1M tokens)',
  'settings.pricingHelp': 'Set custom token rates for real-time cost observability. Use $0 for local Ollama or LM Studio models.',
  'settings.provider': 'Provider',
  'settings.model': 'Model',
  'settings.inputPrice': 'Input ($/M)',
  'settings.outputPrice': 'Output ($/M)',
  'settings.inputPriceFor': 'Input price per million tokens for {model}',
  'settings.outputPriceFor': 'Output price per million tokens for {model}',
  'settings.privacyTitle': 'Privacy and secret sanitization',
  'settings.privacyLabel': 'Sanitize passwords, tokens and tool arguments',
  'settings.privacyHelp': 'Masks bearer tokens, AWS credentials and database secrets in the interface.',
  'settings.audioTitle': 'Synthesized web audio',
  'settings.audioLabel': 'Play subtle sound cues',
  'settings.audioHelp': 'Unobtrusive Web Audio chimes for completed tasks, meetings and blocker warnings.',
  'settings.ambientHelp': 'Idle agents may walk to the espresso bar, tell jokes, chat and show light moods.',
  'settings.politicsHelp': 'Off by default. Built-in dialogue stays generic; future live news must carry source and timestamp metadata.',
} as const satisfies Record<string, string>;

const ES: Record<keyof typeof EN, string> = {
  'common.close': 'Cerrar',
  'common.closeDialog': 'Cerrar el diálogo',

  'tasks.createButton': '+ {label}',
  'tasks.dag.director': 'Dirección',
  'tasks.dag.directorDetail': 'Objetivo',
  'tasks.dag.leads': 'Líderes técnicos y de investigación',
  'tasks.dag.leadsDetail': 'Arquitectura y especificaciones',
  'tasks.dag.engineering': 'Equipo de ingeniería',
  'tasks.dag.engineeringDetail': 'Código y herramientas',
  'tasks.dag.qa': 'Laboratorio QA',
  'tasks.dag.qaDetail': 'Seguridad y pruebas',
  'tasks.dag.release': 'Entrega verificada',
  'tasks.cardHint': 'Doble clic para abrir el expediente del agente asignado',
  'tasks.leadHint': 'Abrir el expediente completo de {name}',
  'tasks.blocked': 'Ejecución bloqueada',
  'tasks.deliverablesCount': '{label} ({count})',
  'tasks.author': 'Autor: {name}',
  'tasks.progressLabel': 'Progreso de {task}',
  'taskStatus.PENDING': 'Pendiente',
  'taskStatus.ASSIGNED': 'Asignada',
  'taskStatus.IN_PROGRESS': 'En curso',
  'taskStatus.BLOCKED': 'Bloqueada',
  'taskStatus.REVIEW': 'En revisión',
  'taskStatus.COMPLETED': 'Completada',
  'taskStatus.FAILED': 'Fallida',

  'meetings.live': 'Sesión en vivo',
  'meetings.subtitle': 'Deliberación multiagente, alineación de arquitectura, construcción de consenso y decisiones.',
  'meetings.startedAt': 'Inició a las {time}',
  'meetings.agenda': 'Puntos de la agenda',
  'meetings.agendaItem': '{index}. {item}',
  'meetings.transcript': 'Transcripción de la deliberación',
  'meetings.exchanges': '{count} intercambios',
  'meetings.decisions': 'Consensos y decisiones registrados',
  'meetings.telemetry': 'Telemetría de la reunión',
  'meetings.tokens': 'Tokens consumidos',
  'meetings.cost': 'Costo de la sesión',
  'meetings.tasksSpawned': 'Tareas creadas',
  'meetings.attendees': 'Asistentes sentados ({count})',
  'meetings.participant': 'Participante',
  'meetings.status.SCHEDULED': 'Programada',
  'meetings.status.ACTIVE': 'Activa',
  'meetings.status.CONCLUDED': 'Terminada',

  'meetings.spend.calls': '{count} llamadas al modelo',
  'meetings.spend.inputTokens': 'Tokens de entrada',
  'meetings.spend.outputTokens': 'Tokens de salida',
  'meetings.spend.cost': 'Costo',
  'meetings.spend.loading': 'Cargando el gasto…',
  'meetings.spend.unavailable': 'Este servidor no tiene datos de gasto disponibles.',
  'meetings.spend.simulated': 'Simulado',
  'meetings.spend.asOf': 'Actualizado a las {time}',
  'meetings.spend.table': 'Gasto por reunión',
  'meetings.spend.tableTitle': 'Reunión',
  'meetings.spend.tableTokens': 'Tokens',
  'meetings.spend.tableCost': 'Costo',
  'meetings.spend.unattributedRow': 'Sin atribuir a una reunión',
  'meetings.spend.incomplete': 'El historial puede estar incompleto.',

  'timeline.searchLabel': 'Buscar en la línea de tiempo',
  'timeline.categories': 'Categorías de eventos',
  'timeline.agentFilter': 'Filtrar eventos por agente',
  'timeline.expand': 'Mostrar el detalle del evento',
  'timeline.collapse': 'Ocultar el detalle del evento',

  'floor.subtitle': 'Las salas elásticas solo se crean cuando todas las salas de reunión visibles están ocupadas.',
  'floor.privateTopic': 'Colaboración privada en el piso secreto',
  'floor.agentsUpstairs': '{count} agentes arriba',
  'floor.reservation.RESERVED': 'Reservada',
  'floor.reservation.ACTIVE': 'Activa',

  'newTask.objectivePlaceholder': 'p. ej. Implementar un despachador de webhooks con reintentos exponenciales',
  'newTask.descriptionPlaceholder': 'Describe los entregables técnicos, las restricciones de seguridad y los endpoints...',
  'newTask.defaultDescription': 'Objetivo personalizado enviado desde la consola.',
  'newTask.agentOption': '{name}, {role}',
  'newTask.roleFallback.backend_engineer': 'Ingeniería backend',
  'newTask.roleFallback.frontend_engineer': 'Ingeniería frontend',
  'newTask.roleFallback.research_lead': 'Líder de investigación',
  'newTask.roleFallback.qa_engineer': 'QA y automatización de pruebas',
  'newTask.roleFallback.security_analyst': 'Análisis de seguridad',
  'newTask.preset.security.title': 'Auditoría de seguridad y búsqueda de secretos expuestos',
  'newTask.preset.security.description': 'Revisar el código y el historial de git en busca de tokens, credenciales OAuth y alertas CVE.',
  'newTask.preset.database.title': 'Migración de PostgreSQL y ajuste de índices',
  'newTask.preset.database.description': 'Escribir los scripts DDL de migración, agregar índices compuestos y medir la latencia p99.',
  'newTask.preset.rag.title': 'Pipeline de índice vectorial RAG e ingesta de citas',
  'newTask.preset.rag.description': 'Llevar la documentación técnica de RFC a un almacén vectorial con búsquedas en menos de un segundo.',
  'newTask.preset.e2e.title': 'Suite automática de regresión visual con Playwright',
  'newTask.preset.e2e.description': 'Ejecutar pruebas en navegador headless en todas las vistas de escritorio y móvil.',

  'settings.close': 'Cerrar la configuración',
  'settings.pricingTitle': 'Catálogo de precios de modelos LLM ($ por 1M de tokens)',
  'settings.pricingHelp': 'Define tarifas propias por token para observar costos en tiempo real. Usa $0 para modelos locales de Ollama o LM Studio.',
  'settings.provider': 'Proveedor',
  'settings.model': 'Modelo',
  'settings.inputPrice': 'Entrada ($/M)',
  'settings.outputPrice': 'Salida ($/M)',
  'settings.inputPriceFor': 'Precio de entrada por millón de tokens de {model}',
  'settings.outputPriceFor': 'Precio de salida por millón de tokens de {model}',
  'settings.privacyTitle': 'Privacidad y limpieza de secretos',
  'settings.privacyLabel': 'Ocultar contraseñas, tokens y argumentos de herramientas',
  'settings.privacyHelp': 'Enmascara tokens bearer, credenciales de AWS y secretos de bases de datos en la interfaz.',
  'settings.audioTitle': 'Audio web sintetizado',
  'settings.audioLabel': 'Reproducir avisos sonoros sutiles',
  'settings.audioHelp': 'Sonidos discretos de Web Audio para tareas completadas, reuniones y bloqueos.',
  'settings.ambientHelp': 'Los agentes sin trabajo pueden ir al café, contar chistes, conversar y mostrar su ánimo.',
  'settings.politicsHelp': 'Apagado por defecto. Los diálogos incluidos son genéricos; las noticias en vivo futuras deben llevar fuente y fecha.',
};

export const VIEWS_MESSAGES = { en: EN, es: ES };
